// Export all services from a single file
export { default as authService } from './authService';
export { default as documentService } from './documentService';
export { default as advisorService } from './advisorService';
export { default as commentService } from './commentService';
export { default as submissionService } from './submissionService';
export { default as statisticsService } from './statisticsService';
export { default as searchService } from './searchService';
export { default as notificationService } from './notificationService';
export { default as studentService } from './studentService';
export { default as storageService } from './storageService';
export { default as healthService } from './healthService';
export { default as debugService } from './debugService';
export { default as studentProfileService } from './studentProfileService';
export { default as courseService } from './courseService';
export { default as ratingService } from './ratingService';
export { default as api } from './api';
